Integrate raw events
quixai/quix-streams pull request #120
Opened 2023-05-16 09:52 UTC by harisbotic

Integrate raw events

2023-05-17 16:44 UTC, peter-quix commented on src/CsharpClient/QuixStreams.Streaming/StreamConsumer.cs
> +                Timestamp = DateTime.UtcNow.ToUnixNanoseconds() ,
We need to use kafka message timestamp in this case, must be the same value regardless of how many times we read the same event. Preference would be that the Kafka specific logic only lives where kafka specific code currently does and not introduce at new places.

We want to disentangle ourselves from kafka in future for more supported brokers.


You might be able to get the required information in OnStreamPackageReceived handler, but that would also require polluting this class with Kafka specific logic.

2023-05-17 16:44 UTC, peter-quix commented on src/CsharpClient/QuixStreams.Telemetry/Kafka/KafkaStreamPipelineFactory.cs
> +            if (transportContext.GetKey() != null)
Can reduce arrow coding here and avoid retrieving key twice.

```
var key = transportContext.GetKey();
if (key == null) return false;
streamId = Encoding.UTF8.GetString(key);
```

2023-05-24 12:24 UTC, peter-quix requested changes

2023-05-24 12:24 UTC, peter-quix commented on src/CsharpClient/QuixStreams.Transport.Kafka/KafkaHelper.cs
> +                {KnownTransportContextKeys.BrokerMessageTime, consumeResult.Message.Timestamp.UtcDateTime},
lets delete KnownKafkaTransportContextKeys.DateTime

2023-05-24 12:24 UTC, peter-quix commented on src/CsharpClient/QuixStreams.Telemetry/Core/StreamPipeline.cs
> +        public const string DefaultStreamId = "DEFAULT";
I'm thinking the value here would be better to be something like NO_STREAM_ID or similar, rather than default.

2023-05-24 19:57 UTC, harisbotic commented on src/CsharpClient/QuixStreams.Telemetry/Core/StreamPipeline.cs
> +        public const string DefaultStreamId = "DEFAULT";
Makes sense to me. I changed it to 
`public const string DefaultStreamIdWhenMissing = "NO_STREAM_ID";`
Let me know if you got something better

2023-05-25 08:51 UTC, peter-quix approved these changes, later dismissed

2023-05-25 09:22 UTC, peter-quix submitted a review, later dismissed

2023-05-25 10:39 UTC, peter-quix approved these changes

2023-05-25 10:53 UTC, merged