Implement RocksDb state storage
quixai/quix-streams pull request #161
Opened 2023-07-20 11:03 UTC by harisbotic

Implement RocksDb state storage

2023-07-27 15:03 UTC, peter-quix requested changes
As discussed, we need to remove the RocksDB python part, as the underlying library relies on emitting new types which is not supported by NAOT.

2023-07-27 15:03 UTC, peter-quix commented on src/CsharpClient/QuixStreams.State.ParallelWriteTest/Program.cs
> -            var storage = new LocalFileStorage();
prob can generalize this a bit

2023-07-27 15:03 UTC, peter-quix commented on src/CsharpClient/QuixStreams.State/Storage/FileStorage/BaseFileStorage.cs
> +        public IStateStorage GetOrCreateSubStorage(string subStorageName, string dbName = null)
Hm, original idea was to use the substoragename in places wherever a name is needed. I'll check the rest of the code, but this looks suspicious.

Edit: Lets have a chat to understand the need for this. I saw you using it in relation to the upcoming partition support.

2023-09-28 18:45 UTC, peter-quix commented on src/CsharpClient/QuixStreams.State/Serializers/Crc32.cs
We can prob remove this, this used to be used for filestorage to make sure file was properly written to disk, but with RocksDB this is on the db

2023-09-29 11:12 UTC, peter-quix commented on src/CsharpClient/QuixStreams.Streaming.UnitTests/AppShould.cs
> +            var manager = App.GetStateStorageRootDir();
Not a manager any more, same applies to state name

2023-10-03 21:14 UTC, harisbotic commented on src/CsharpClient/QuixStreams.State/Serializers/Crc32.cs
Its used in classes, and I could remove that too,
but since we are going to bring LocalFileStorage back, lets just keep it as we will need it

2023-10-03 21:50 UTC, peter-quix approved these changes
Approved, as per our discussion, further testing will be done on 0.6.0 branch and reimplementation of statestorage + python changes

2023-10-05 12:26 UTC, merged