add some examples (uses auto-create-topics)
quixai/quix-streams pull request #203
Opened 2023-10-19 13:38 UTC by tim-quix

Created some examples along with some boilerplate/helpers to easily get started. 

See `StreamingDataFrame/examples/README.md` for details.

2023-10-20 15:20 UTC, ghost commented on src/StreamingDataFrames/examples/platforms/quix/timeseries_row_producer.py
> +try:
You can use `with RowProducer ...` instead of `try-finally` here. 
It flushes itself on closing

2023-10-20 15:21 UTC, tim-quix commented on src/StreamingDataFrames/examples/platforms/quix/timeseries_row_producer.py
> +try:
Oh good catch!

2023-10-23 13:55 UTC, daniil-quix requested changes

2023-10-23 13:55 UTC, daniil-quix commented on src/StreamingDataFrames/examples/bank_example/quix_platform_version/producer.py
> +    producer.flush(10)
Producer can be used as a context manager

2023-10-23 13:55 UTC, daniil-quix commented on src/StreamingDataFrames/examples/bank_example/quix_platform_version/alternate_producer.py
I suggest we remove this example for now.
RowProducer is not really supposed to be used outside of SDF right now.

The need to pass all of these dummy params to `Row` makes it not really usable, so there's no value in having it as an example.

We can add it as an example when we make it more user-friendly.

2023-10-23 13:55 UTC, ghost commented on src/StreamingDataFrames/examples/bank_example/json_version/producer.py
> +try:
Same, Producer can be used as a context manager

2023-10-24 12:06 UTC, daniil-quix approved these changes
Looks good to go!

2023-10-24 13:40 UTC, merged