Implement handling messages without keys
quixai/quix-streams pull request #306
Opened 2024-03-01 08:47 UTC by harisbotic

#### Allow events with `null` keys overall in StreamingDataFrame.
* `null` is still a value, plus users can change the key to something else

#### Skip events with `null` keys in Windows and log warnings:
* Messages with the `null` keys can be sent to random partitions (depending on the partitioner).
* Therefore the result of the window with the `null` key can be a random value because of it
* If the events have `null` keys, they must be re-keyed before processing them in the window.

2024-03-01 12:12 UTC, daniil-quix requested changes

2024-03-01 12:12 UTC, daniil-quix commented on quixstreams/dataframe/windows/time_based.py
> +        if not key:
Using `not` is incorrect here because it can filter out keys like `0` and `False`, which are valid values.

Use `is None` check instead

2024-03-01 13:17 UTC, harisbotic commented on quixstreams/dataframe/windows/time_based.py
> +                f"Message offset: {ctx.offset}, partition: {ctx.partition}."
Should we add a `ctx.topic` here as well?

2024-03-04 11:08 UTC, daniil-quix approved these changes

2024-03-04 11:09 UTC, merged