add drop feature
quixai/quix-streams pull request #393
Opened 2024-07-02 18:06 UTC by tim-quix

Add the ability to drop a column or list of columns from a `StreamingDataFrame` via:

 `SDF.drop("col_a")` or `SDF.drop(["col_a", "col_b"])`

2024-07-03 09:13 UTC, daniil-quix requested changes

2024-07-03 09:13 UTC, ghost commented on quixstreams/dataframe/dataframe.py
> +    def drop(self, columns: Union[str, List[str]]) -> Self:
Hey, we can use variadic params instead of `Union` here:
```
def drop(self, *columns: str) -> Self:
```

2024-07-03 18:07 UTC, tim-quix commented on quixstreams/dataframe/dataframe.py
> +    def drop(self, columns: Union[str, List[str]]) -> Self:
Discussed this and we will leave as is =)

2024-07-17 18:26 UTC, daniil-quix approved these changes

2024-07-17 18:26 UTC, merged

2024-07-17 20:26 UTC, stereosky commented
Absolutely perfect timing for this as I needed it tomorrow 🙌🏽