Restructured readme and broke out optional info into supplementary topics
quixai/quix-streams pull request #46
Opened 2023-02-27 09:37 UTC by merlin-quix

Updated the READMDE so that the libraries features are more prominent and understandable with code samples to illustrate how they work

Also split out lower-priority information into supplementary topics. For example:

- "What is time series data?" -> `what-is-timeseries.md` — many readers won't need this information so better to not let it clutter the main READMDE. 
- "Installing on M1/M2?" -> `mac-m1-m2-install.md` — again, this is currently "workaround" documentation (also very lengthy) and wont concern many readers (on Windows, Linux, or Intel Mac)
- "Architecture Notes" -> `arch-notes.md` — supplementary information that wont interest everyone.

Additionally, the "Prepare your Kafka Cluster" section did not provide any information on how to prepare anything, rather it's purpose seemed to be simply to communicate the message "We use Kafka".

I reworked this section to provide basic instructions for a local Kafka install to help people test the library quickly.

2023-02-27 10:07 UTC, tbedford requested changes
Not reviewed all of it, but noticed the code in the README now seems to be for an old version of the SDK?

2023-02-27 10:07 UTC, tbedford commented on README.md
> +    topic_producer = client.create_topic_producer("data")
should this be `get_topic_producer`?

2023-02-27 10:07 UTC, tbedford commented on README.md
> +    stream.parameters \
Should this be `stream.timeseries`?

I'm not sure how, but this looks like old code?

2023-02-27 10:57 UTC, peter-quix commented
> Not reviewed all of it, but noticed the code in the README now seems to be for an old version of the SDK?

Yeah, I think before we review this readme it would worth updating it to latest

2023-02-27 13:51 UTC, tomas-quix commented
Are you sure putting Getting started after library features?

2023-02-27 15:02 UTC, merlin-quix commented
> Are you sure putting Getting started after library features?

No - It doesn't have to be. I can reorder if you want. The "real" Quick Start is in the online docs anyway (which I am linking to)

2023-02-27 15:07 UTC, merlin-quix commented on README.md
> +    stream.parameters \
fixed these instances. Not familiar enough with all the library changes to catch everything though

2023-02-27 15:07 UTC, merlin-quix commented on README.md
> +    topic_producer = client.create_topic_producer("data")
I don't know. I'll take your word for it though.

2023-02-27 15:11 UTC, merlin-quix commented
> > Not reviewed all of it, but noticed the code in the README now seems to be for an old version of the SDK?
> 
> Yeah, I think before we review this readme it would worth updating it to latest

Would be good to review it next to the [announcement copy](https://quix.io/blog/open-sourcing-quix-streams/?x-craft-preview=8jrofzmWCY&token=YYPO-EV_WzWuW3Erzm0aCXb5__a8ZAca) as both are designed to use the same feature lists w/ samples.

2023-03-01 07:51 UTC, PatrickMiraP commented
New arch-notes.md file is not correctly linked to the Readme. For instance where we are saying "Quix Streams is [designed to be extended](#interoperability-wrappers) to multiple programming languages.". 

Probably Contribution Guide section could be another good place to link to the new file.

2023-03-01 10:53 UTC, SteveRosam commented
Docs build including this branch is here:
https://quixdocsdev.blob.core.windows.net/pr91/sdk-intro.html

2023-03-01 11:00 UTC, PatrickMiraP commented
About removing "What is time series data" after "What is Quix Streams" section, there are some thoughts here in slack https://quixworld.slack.com/archives/C01U8DHH67J/p1677656326060989?thread_ts=1677218529.712249&cid=C01U8DHH67J

If we return it to the main readme, I will keep it in the same position. This section only makes sense to improve the context of "What is Quix Streams".

2023-03-01 18:24 UTC, peter-quix approved these changes

2023-03-01 18:26 UTC, peter-quix requested changes
The Readme.md regressed in several places talking about output and inputs, etc.

2023-03-01 19:04 UTC, peter-quix approved these changes

2023-03-01 19:05 UTC, merged